# Generated by Django 5.1.4 on 2026-06-04 06:16

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0008_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('claim_key', models.CharField(blank=True, help_text="OIDC claim to match (e.g. 'groups' or 'department').", max_length=255)),
                ('claim_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='A user whose claim contains any of these values is a member.', size=None)),
                ('members', models.ManyToManyField(blank=True, related_name='access_groups', to=settings.AUTH_USER_MODEL)),
                ('pools', models.ManyToManyField(blank=True, related_name='access_groups', to='catalog.resourcepool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
