# Generated by Django 5.1.4 on 2026-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_strikesetting_user_blocked_permanently_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
