# Generated by Django 5.1.4 on 2026-06-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_language'),
        ('lending', '0011_cartsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes', to='lending.booking'),
        ),
    ]
