# Generated by Django 5.1.4 on 2026-06-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_strike_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=1095)),
            ],
            options={
                'verbose_name': 'retention setting',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
