# Generated by Django 5.1.4 on 2026-06-01 14:36

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lending_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10)),
                ('min_duration', models.PositiveIntegerField(blank=True, help_text='Minimum lending duration in the lending_type unit (overrides pool default).', null=True)),
                ('max_duration', models.PositiveIntegerField(blank=True, help_text='Maximum lending duration in the lending_type unit (overrides pool default).', null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('attribute_schema', models.JSONField(blank=True, default=catalog.models.default_attribute_schema)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pool_id', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('lead_time_hours', models.PositiveIntegerField(default=0)),
                ('default_min_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_min_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('default_max_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('products', models.ManyToManyField(blank=True, related_name='categories', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('products', models.ManyToManyField(blank=True, related_name='product_sets', to='catalog.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.producttype'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('defective', 'Defective'), ('retired', 'Retired')], default='available', max_length=12)),
                ('inventory_number', models.CharField(max_length=255, unique=True)),
                ('qr_code_id', models.CharField(max_length=255, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('procurement_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('procuring_institution', models.CharField(blank=True, max_length=255)),
                ('owning_institution', models.CharField(blank=True, max_length=255)),
                ('lending_type', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], max_length=10)),
                ('min_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('max_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='catalog.product')),
                ('resource_pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='catalog.resourcepool')),
            ],
            options={
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='sections', to='catalog.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
