# Generated by Django 5.1.4 on 2026-06-02 15:18

import catalog.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='closed_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=catalog.models.default_closed_weekdays, size=None),
        ),
    ]
