# Generated by Django 5.1.4 on 2026-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_resourcepool_closed_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='defect_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
