# Generated by Django 5.1.4 on 2026-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='max_booking_months',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
