# Generated by Django 5.1.4 on 2026-06-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_resourcepool_max_booking_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='resource_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sets', to='catalog.resourcepool'),
        ),
        migrations.AddField(
            model_name='section',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='sections', to='catalog.productset'),
        ),
    ]
