# Generated by Django 5.1.4 on 2026-06-07 20:30

from django.db import migrations, models


def backfill_positions(apps, schema_editor):
    """Give existing rows a stable order matching the previous alphabetical sort."""
    for model_name in ("Category", "Section"):
        model = apps.get_model("catalog", model_name)
        for index, obj in enumerate(model.objects.order_by("title")):
            model.objects.filter(pk=obj.pk).update(position=index)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productset_resource_pool_section_sets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'title'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position', 'title']},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_positions, migrations.RunPython.noop),
    ]
