# Generated by Django 5.1.4 on 2026-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_info',
            field=models.TextField(blank=True),
        ),
    ]
