# Generated by Django 5.1.4 on 2026-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_return_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
