# Generated by Django 5.1.4 on 2026-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_resource_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'welcome setting',
            },
        ),
    ]
