# Generated by Django 5.1.4 on 2026-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomesetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
