# Generated by Django 5.1.4 on 2026-06-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_welcomesetting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popular', models.BooleanField(default=True)),
                ('show_new_arrivals', models.BooleanField(default=True)),
                ('new_product_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'shop setting',
            },
        ),
    ]
