# Generated by Django 5.1.4 on 2026-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_backfill_translation_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='notify_on_defect',
            field=models.BooleanField(default=True),
        ),
    ]
