# Generated by Django 5.1.4 on 2026-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_resourcepool_notify_on_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='defect_gitlab_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resourcepool',
            name='defect_gitlab_url',
            field=models.URLField(blank=True),
        ),
    ]
