# Generated by Django 5.1.4 on 2026-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_resourcepool_defect_gitlab_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedefect',
            name='gitlab_issue_url',
            field=models.URLField(blank=True),
        ),
    ]
