# Generated by Django 5.1.4 on 2026-06-22 19:17

import catalog.fields
from django.db import migrations


def _transform_tokens(schema_editor, transform):
    """Rewrite every stored token in place via raw SQL, bypassing the field's
    own encrypt/decrypt so we can move plaintext → ciphertext (and back)."""
    table = "catalog_resourcepool"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, defect_gitlab_token FROM {table} "
            "WHERE defect_gitlab_token <> ''"
        )
        rows = cursor.fetchall()
        for pk, value in rows:
            cursor.execute(
                f"UPDATE {table} SET defect_gitlab_token = %s WHERE id = %s",
                [transform(value), pk],
            )


def encrypt_existing(apps, schema_editor):
    from catalog.encryption import encrypt

    _transform_tokens(schema_editor, encrypt)


def decrypt_existing(apps, schema_editor):
    from catalog.encryption import decrypt

    _transform_tokens(schema_editor, decrypt)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_resourcedefect_gitlab_issue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepool',
            name='defect_gitlab_token',
            field=catalog.fields.EncryptedTextField(blank=True, default=''),
        ),
        # Encrypt tokens that were stored in plaintext before this change.
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
