# Generated by Django 5.1.4 on 2026-06-23 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_resourcepool_defect_gitlab_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
