# Generated by Django 5.1.4 on 2026-06-23 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_category_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='set_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
