# Generated by Django 5.1.4 on 2026-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_privacy_retention_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='require_booking_note',
            field=models.BooleanField(default=False),
        ),
    ]
