# Generated by Django 5.1.4 on 2026-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_resourcepool_require_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='notify_on_cancellation',
            field=models.BooleanField(default=True),
        ),
    ]
