# Generated by Django 5.1.4 on 2026-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_resourcepool_notify_on_cancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_intro', models.TextField(blank=True)),
                ('reservation_intro_en', models.TextField(blank=True, null=True)),
                ('reservation_intro_de', models.TextField(blank=True, null=True)),
                ('reservation_footer', models.TextField(blank=True)),
                ('reservation_footer_en', models.TextField(blank=True, null=True)),
                ('reservation_footer_de', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notification setting',
            },
        ),
    ]
