# Generated by Django 5.1.4 on 2026-07-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='email_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcepool',
            name='email_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcepool',
            name='email_note_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
