# Generated by Django 5.1.4 on 2026-07-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_resourcepool_email_note_resourcepool_email_note_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='confirmation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='confirmation_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='confirmation_note_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
