# Generated by Django 5.1.4 on 2026-07-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_notificationsetting_confirmation_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='confirmation_note',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='confirmation_note_de',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='confirmation_note_en',
        ),
    ]
