# Generated by Django 5.1.4 on 2026-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_remove_notificationsetting_confirmation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='cancellation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='cancellation_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='cancellation_note_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='defect_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='defect_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='defect_note_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='reminder_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='reminder_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='reminder_note_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='rescheduled_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='rescheduled_note_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='rescheduled_note_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
