# Generated by Django 5.1.4 on 2026-07-14 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_bilingual_attr_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_gap',
            field=models.PositiveIntegerField(default=0, help_text='Minimum gap between two bookings of a device, in the lending_type unit (days/hours). 0 = no gap.'),
        ),
        migrations.AddField(
            model_name='product',
            name='missing_notice_lead',
            field=models.PositiveIntegerField(default=0, help_text='How far before pickup to warn the next borrower that the product is missing, in the lending_type unit. 0 = never notify.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='condition_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='condition_rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
