# Generated by Django 5.1.4 on 2026-09-18 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
