# Generated by Django 5.1.4 on 2026-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_product_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcepool',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
