# Generated by Django 5.1.4 on 2026-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_resourcepool_accent_color_resourcepool_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepool',
            name='email_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='de', help_text="Language for emails to this pool's contact and its lenders.", max_length=10),
        ),
    ]
