# Generated by Django 5.1.4 on 2026-09-24 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_resourcepool_email_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complementary_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='complementary_products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
