# Generated by Django 5.1.4 on 2026-09-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_product_complementary_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='confirmation_send_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
