# Generated by Django 5.1.4 on 2026-10-01 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_rich_text_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_types/'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='product_type_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='section',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='sections', to='catalog.producttype'),
        ),
    ]
