# Generated by Django 5.1.4 on 2026-10-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_categories_to_product_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='section',
            name='category_order',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
