# Generated by Django 5.1.4 on 2026-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_product_types_to_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__isnull': True}, related_name='sections', to='catalog.category'),
        ),
    ]
