# Generated by Django 5.1.4 on 2026-10-07 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_dedupe_category_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='unique_live_category_name_per_parent', violation_error_message='A category with this name already exists here.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('name',), name='unique_live_root_category_name', violation_error_message='A top-level category with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name_en'), name='unique_live_category_name_per_parent-name_en', violation_error_message='A category with this name already exists here.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name_de'), name='unique_live_category_name_per_parent-name_de', violation_error_message='A category with this name already exists here.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('name_en',), name='unique_live_root_category_name-name_en', violation_error_message='A top-level category with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('name_de',), name='unique_live_root_category_name-name_de', violation_error_message='A top-level category with this name already exists.'),
        ),
    ]
