# Generated by Django 5.1.4 on 2026-10-07 23:06

"""#78 (ADR-0011): drop the ADR-0010 type navigation once 0052 has copied it
into categories.

Irreversible in practice: rolling back re-creates the columns empty, so the
type images, order and section assignments are gone (back up the database
and the media volume first, docs/INSTALL.md §7.3). Removing ``image`` only
drops the column; the stored files stay, because the categories made by 0052
reference the same paths.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_category_unique_live_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='position',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='product_type_order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='product_types',
        ),
    ]
