# Generated by Django 5.1.4 on 2026-10-08 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_product_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='max_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum lending duration of this device (empty = inherit from product/pool).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='min_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum lending duration of this device (empty = inherit from product/pool).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
