# Generated by Django 5.1.4 on 2026-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_resource_duration_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
