# Generated by Django 5.1.4 on 2026-09-29 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CspViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive', models.CharField(max_length=100)),
                ('blocked', models.CharField(blank=True, max_length=200)),
                ('page', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CSP violation',
                'verbose_name_plural': 'CSP violations',
                'ordering': ['-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('directive', 'blocked', 'page'), name='unique_csp_violation')],
            },
        ),
    ]
