# Generated by Django 5.1.4 on 2026-06-01 15:13

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_image'),
        ('lending', '0001_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('handed_out', 'Handed out'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('is_active', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lending.booking')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='catalog.resource')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('resource', '='), ('period', '&&')], name='no_overlapping_active_bookings')],
            },
        ),
    ]
