# Generated by Django 5.1.4 on 2026-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('handed_out', 'Handed out'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='cart', max_length=12),
        ),
    ]
