# Generated by Django 5.1.4 on 2026-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_backfill_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='handed_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
