# Generated by Django 5.1.4 on 2026-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_bookingitem_handed_out_at_bookingitem_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overdue_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
