# Generated by Django 5.1.4 on 2026-06-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_stamp_legacy_item_handouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('overdue_pickups', models.PositiveSmallIntegerField(default=0)),
                ('overdue_returns', models.PositiveSmallIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lending.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
