# Generated by Django 5.1.4 on 2026-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_bookingreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='DE', max_length=2)),
                ('subdivision', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name': 'holiday setting',
            },
        ),
    ]
