# Generated by Django 5.1.4 on 2026-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_holidaysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_minutes', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'cart setting',
            },
        ),
    ]
