# Generated by Django 5.1.4 on 2026-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0011_cartsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='missing_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
