# Generated by Django 5.1.4 on 2026-09-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_notificationsetting_confirmation_send_time'),
        ('lending', '0012_bookingitem_missing_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_mailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.resourcepool'),
        ),
    ]
