# Generated by Django 5.1.4 on 2026-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0014_split_multi_pool_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_override',
            field=models.BooleanField(default=False),
        ),
    ]
